@startuml
start
:创建索引;
:**Document.index() 初始化文档索引关系**;
repeat
  if (文档是否包含索引?) then (包含)
    :文档增加索引关键词;
    :索引增加文档ID;
  endif
repeat while (遍历已有多词索引)
repeat
  :保存索引;
repeat while (遍历文档索引关系)

stop
@enduml
